---
###############################################################################
# The tuning values listed are for demonstration purposes only. 
# These values are a suggested starting point and are not definitive. 
# Customers should perform their own testing, to validate and verify their own
# settings, in order to meet their system needs.
###############################################################################
global:
  license: '' # Set to 'accept' after reviewing all license agreements
  images:
    registry: us.icr.io
    imageLibrary: foo-library
    imagePrefix: test_
    imageTag: latest
    pullPolicy: Always
  imagePullSecret:
    registry: us.icr.io
    username: '' # IAM username for IBM Container Registry
    password: '' # IAM API Key for IBM Container Registry
  database:
    ## Database connection properties
    type: DB2
    dbName: DATABASE
    hostname: ''
    port: 50000
    username: db2admin
    # Name of pre-created secret containing database credentals
    credsSecretName: ''
    # The XOR-encrypted password injected into Liberty configuration
    wlp_psw: "{xor}Oz1tPjsyNjE="
    # The SPM-encrypted password injected into Bootstrap.properties
    spm_psw: "5itAmT5UzH7wR6kvkYqkTw=="
    # Oracle Service name, where applicable
    serviceName: ''
    ssl:
      enabled: false
      # Name of the secret containing the database TLS certificate
      secretName: ''
      # Key in the above secret with the certificate
      secretKey: db2admin.arm
  ingress:
    annotations:
      ingress.bluemix.net/ALB-ID: ''
    enabled: true
    hostname: spm.<cluster_name>-<hash>-0000.<region>.containers.appdomain.cloud
    tlsSecretName: default-us-icr-io
  apps: {}
    # config:
    #   curam:
    #     mqTuning:
    #      resources:
    #        requests:
    #          cpu: 1
    #          memory: 1024Mi
    #        limits:
    #          cpu: 1
    #          memory: 1024Mi
    #     producerTuning:
    #       replicaCount: 1
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 3584Mi
    #         limits:
    #           cpu: 2
    #           memory: 3584Mi
    #       jvm: ['-Xms2560M','-Xmx2560M','-Xmn1536M']
    #       coreThreads: 8
    #       maxThreads: 8
    #       mqMaxPoolSize: 9
    #       mqMinPoolSize: 9
    #       mqNumConnectionsPerThreadLocal: 6
    #       maxJMSConnectionsPerThread: 6
    #       curamdb_maxPoolSize: 17
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 9
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 9
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    #     consumerTuning:
    #       replicaCount: 1
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 2048Mi
    #         limits:
    #           cpu: 2
    #           memory: 2048Mi
    #       jvm: ['-Xms1600M','-Xmx1600M','-Xmn960M','-verbose:sizes']
    #       coreThreads: 9
    #       maxThreads: 9
    #       mqMaxPoolSize: 10
    #       mqMinPoolSize: 10
    #       mqNumConnectionsPerThreadLocal: 6
    #       maxJMSConnectionsPerThread: 6
    #       maxEndPoints_DPErrorAS: 1
    #       maxEndPoints_WorkflowErrorAS: 1
    #       maxEndPoints_CuramDeadMessageQueueAS: 1
    #       maxEndPoints_DPEnactmentAS: 9
    #       maxEndPoints_WorkflowActivityAS: 9
    #       maxEndPoints_WorkflowEnactmentAS: 9
    #       curamdb_maxPoolSize: 19
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 9
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 1
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    #   rest:
    #     mqTuning:
    #      resources:
    #        requests:
    #          cpu: 1
    #          memory: 1024Mi
    #        limits:
    #          cpu: 1
    #          memory: 1024Mi
    #     producerTuning:
    #       replicaCount: 3
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 3584Mi
    #         limits:
    #           cpu: 2
    #           memory: 3584Mi
    #       jvm: ['-Xms2560M','-Xmx2560M','-Xmn1536M']
    #       coreThreads: 8
    #       maxThreads: 8
    #       mqMaxPoolSize: 9
    #       mqMinPoolSize: 9
    #       mqNumConnectionsPerThreadLocal: 6
    #       maxJMSConnectionsPerThread: 6
    #       curamdb_maxPoolSize: 17
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 9
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 9
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    #     consumerTuning:
    #       replicaCount: 6
    #       resources:
    #         requests:
    #           cpu: 2
    #           memory: 2048Mi
    #         limits:
    #           cpu: 2
    #           memory: 2048Mi
    #       jvm: ['-Xms1600M','-Xmx1600M','-Xmn960M','-verbose:sizes']
    #       coreThreads: 9
    #       maxThreads: 9
    #       mqMaxPoolSize: 10
    #       mqMinPoolSize: 10
    #       mqNumConnectionsPerThreadLocal: 6
    #       maxJMSConnectionsPerThread: 6
    #       maxEndPoints_DPErrorAS: 1
    #       maxEndPoints_WorkflowErrorAS: 1
    #       maxEndPoints_CuramDeadMessageQueueAS: 1
    #       maxEndPoints_DPEnactmentAS: 9
    #       maxEndPoints_WorkflowActivityAS: 9
    #       maxEndPoints_WorkflowEnactmentAS: 9
    #       curamdb_maxPoolSize: 19
    #       curamdb_numConnectionsPerThreadLocal: 2
    #       curamdb_purgePolicy: EntirePool
    #       curamdb_statementCacheSize: 1000
    #       curamtimerdb_maxPoolSize: 9
    #       curamtimerdb_numConnectionsPerThreadLocal: 2
    #       curamtimerdb_purgePolicy: EntirePool
    #       curamtimerdb_statementCacheSize: 1000
    #       curamsessdb_maxPoolSize: 1
    #       curamsessdb_numConnectionsPerThreadLocal: 2
    #       curamsessdb_purgePolicy: EntirePool
    #       curamsessdb_statementCacheSize: 1000
    
    #   citizenportal:
    #     enabled: false
    #   curamwebservices:
    #     enabled: false
    #   curambirtviewer:
    #     enabled: false

# Override values in 'apps' Chart
apps: {}
#   replicaCount: 1
#   initialDelaySeconds: 60
#   loginConfig:
#     trace: true
#   sessionConfig:
#     sessionTimeout: 30m
#     transactionTimeout: 3m
#   defaultResources:
#     requests:
#       cpu: 0.5
#       memory: 768Mi
#     limits:
#       cpu: 0.75
#       memory: 1Gi

# Override values in 'batch' Chart
batch: {}
#   programs:
#     queued:
#       schedule: "*/30 * * * *"

# Override values in 'uawebapp' Chart
uawebapp: {}
#   replicaCount: 1
#   imageConfig:
#     library: ''
#     name: ''
#     tag: latest
#   readinessProbe:
#     path: /universal/
#   ingressPath: /universal
#   resources:
#     requests:
#       cpu: 1
#       memory: 1024Mi
#     limits:
#       cpu: 1
#       memory: 1024Mi

# Override values in 'web' Chart
web: {}
#   replicaCount: 1
#   readinessProbe:
#     path: /CuramStatic/
#   ingressPath: /CuramStatic
#   resources:
#     requests:
#       cpu: 1
#       memory: 1024Mi
#     limits:
#       cpu: 1
#       memory: 1024Mi

# Override values in 'xmlserver' Chart
xmlserver: {}
#   replicaCount: 6
#   jvm:
#      maxMemory: '768m'
#      threadStackSize: '-Xss4m'
#      jvmOptions: ''
#   config:
#      socketTimeout: 60000
#      threadPoolQueueSize: 200
#      threadPoolSize: 5
#   resources:
#     requests:
#       cpu: 2
#       memory: 1000Mi
#     limits:
#       cpu: 2
#       memory: 1000Mi
