###############################################################################
# Copyright 2019,2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
apiVersion: v2
kubeVersion: ">=1.19"
appVersion: "8.0.0.0"
name: web
description: |-
  Chart for SPM webserver within a Kubernetes Cluster

  Documentation
  For complete documentation please see the chart README

  License
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0
version: 21.9.0
maintainers:
  - name: IBM
  - name: Cúram SPM Dev Team
    url: https://github.com/IBM/spm-kubernetes
sources:
  - https://github.com/IBM/spm-kubernetes
keywords:
  - Liberty
  - Minikube
  - IKS
  - OpenShift
  - RHOCP
  - Curam
  - SPM
  - amd64
  - deploy
  - DevOps
  - Commercial
  - Limited
  - Middleware
home: https://www.ibm.com/watson-health/solutions/social-program-management
icon: https://avatars2.githubusercontent.com/u/1459110
dependencies:
  - name: ibm-sch
    repository: "@sch"
    version: "^1.2.19"
    alias: sch
    condition: global.sch.enabled
