{{- include "sch.config.init" (list . "spm.sch.chart.config.values") -}}
{{- if and .Values.global.ingress.enabled (not (.Capabilities.APIVersions.Has "route.openshift.io/v1")) }}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end -}}
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "") | nindent 4 }}
  annotations:
    ingress.bluemix.net/ssl-services: {{ include "spm.sslServicesChain" . }}
    ingress.bluemix.net/sticky-cookie-services: {{ include "spm.stickyCookieServicesChain" . }}
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/session-cookie-path: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "150"
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if or .Values.global.ingress.tlsSecretName .Values.global.ingress.generateCert }}
  tls:
    - hosts:
        -  {{ required "When ingress is enabled, you must provide a value for ingress.hostname" .Values.global.ingress.hostname }}
      {{- if .Values.global.ingress.generateCert }}
      secretName: {{ .Release.Name }}-tls
      {{- else }}
      secretName: {{ .Values.global.ingress.tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ required "When ingress is enabled, you must provide a value for ingress.hostname" .Values.global.ingress.hostname }}
      http:
        paths:
          {{- range $name, $app := .Values.global.apps.config }}
            {{- if and $app.enabled $app.ingressPath }}
              {{- include "spm.ingress.item" (dict "caps" $.Capabilities "path" ($app.ingressPath) "name" (printf "%s-apps-%s" $.Release.Name $name) "port" "https") | nindent 10 -}}
            {{- end }}
          {{- end }}
          {{- if .Values.uawebapp.imageConfig.name }}
            {{- include "spm.ingress.item" (dict "caps" .Capabilities "path" (.Values.uawebapp.ingressPath | default "/universal") "name" (printf "%s-uawebapp" .Release.Name) "port" "https") | nindent 10 -}}
          {{- end }}
          {{- if .Values.global.isam.enabled }}
           {{- include "spm.ingress.item" (dict "caps" .Capabilities "path" "/ibm" "name" (printf "%s-apps-curam" .Release.Name) "port" "https") | nindent 10 -}}
          {{- end }}
          {{- include "spm.ingress.item" (dict "caps" .Capabilities "path" (.Values.web.ingressPath | default "/CuramStatic") "name" (printf "%s-web" .Release.Name) "port" "https") | nindent 10 -}}
{{- end }}
